dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
# command to run tests
script:
  - ls -l
after_success:
  - ls -al
  - git init
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://liushilive:${travis_ci_tokens_gitee}@${REF}" master

branches:
  only:
    - master
env:
  global:
    - REF=gitee.com:liushilive/liushilive.git
before_install:
- export TZ='Asia/Shanghai'
